name: GameDay11thMay
description: ''
version: 0.0.1-SNAPSHOT
author: anshuman@simpledatalabs.com
pipelines:
  pipelines/Reformat:
    name: Reformat
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-11 06:53:24'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
  pipelines/Reformat2:
    name: 1_csv.-
    description: null
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-12 09:21:53'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets:
  datasets/all_types:
    name: all_types
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-11 07:04:45'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-11 07:04:45'
      gamedayfabric:
        fabricId: 920
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-11 09:57:39'
  datasets/timestamps:
    name: timestamps
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-11 07:31:52'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-11 07:31:52'
      gamedayfabric:
        fabricId: 920
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-11 09:57:39'
  datasets/malformed_csv:
    name: malformed_csv
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-12 09:22:59'
    physicalDatasets:
      anshuman:
        fabricId: 811
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-12 09:22:59'
      gamedayfabric:
        fabricId: 920
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-12 09:23:04'
jobs: {}
libraries: []
subgraphs: {}
dependencies: []
template: '[]'
